config/routes.rb
Rails.application.routes.draw do

  resources :kurs do
    collection do
      get :updatekur
      get :update_snippet
    end
  end
  root to: 'home#index'
  get '/insints' , to: 'home#index'
  resources :insints do
    collection do
      get :install
      get :uninstall
      get :login
      get :adminindex
      get :setup_script
      get :delete_script
      get :checkint
    end
  end

  constraints SubdomainConstraint do
    get '/dashboard/index' , to: 'dashboard#index'
    get '/dashboard/users', to: 'dashboard#users'
    get '/dashboard/test_email', to: 'dashboard#test_email'
    delete '/dashboard/user_destroy', to: 'dashboard#user_destroy'
  end # constraints

  devise_for :users, controllers: {
    registrations:  'users/registrations',
    sessions:       'users/sessions',
    passwords:      'users/passwords',
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    insint = current_user.insints.first
    if insint.present?
      if insint.inskey.present?
        uri = "http://"+"#{insint.inskey}"+":"+"#{insint.password}"+"@"+"#{insint.subdomen}"+"/admin/products/count.json"
      else
        uri = "http://k-kurs:"+"#{insint.password}"+"@"+"#{insint.subdomen}"+"/admin/products/count.json"
        url = "http://k-kurs:"+"#{insint.password}"+"@"+"#{insint.subdomen}"+"/admin/account.json"
      end
        puts uri
        response = RestClient.get(uri)
        data = JSON.parse(response)
        @product_count = data['count']
    end
  end # index

  def users
    if current_admin
      @q = User.ransack(params[:q])
      @q.sorts = 'id desc' if @q.sorts.empty?
      @users = @q.result.paginate(page: params[:page], per_page: 30)
    else
      redirect_to dashboard_index_path
    end
  end

  def user_destroy
    @user = User.find(params[:user_id])
    @user.destroy
    respond_to do |format|
      format.html { redirect_to dashboard_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def test_email
    User.service_end_email
    # Client.emailizb('fishartel', 29250124, 64 ) #development test
    # Client.emailizb('insales22810', 27968659, 20 ) #production test
    flash[:notice] = 'Отправили'
		redirect_to dashboard_index_path
  end

end # index

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="row">
  <div class="col">
    <h1>Общая информация</h1>
    <p>Добро пожаловать <strong><% if current_admin %> администратор - <%else%><%end%></strong><%=current_user.name %>!</p>
    <p>В вашем магазине товаров <%= @product_count %> шт</p>
    <% if current_admin %><p><%= link_to "Test email", dashboard_test_email_path %> <%= link_to "Загрузить курс в таблицу", updatekur_kurs_path %></p><%end%>
    <p><%= link_to "Обновить сниппет", update_snippet_kurs_path %></p></p>
  </div>
  <div class="col">
  <h3>Интеграция insales</h3>
    <% integracia = current_user.insints.first if current_user.insints.first.present? %>
    <p>Состояние:
      <% if integracia %>настроена<% else %>не настроена<% end %>
      <% if integracia && integracia.status %>и файлы добавлены в магазин<%else%>и файлы не добавлены в магазин<%end%>
    </p>
    <% if current_user.insints.first.present? %>
      <% if current_user.insints.first.inskey.present?%>
        <%= link_to 'Редактировать интеграцию', edit_insint_path(current_user.insints.first.id), class: 'btn btn-outline-primary mb-3' %>
        <% if current_user.insints.first.status == false ||  current_user.insints.first.status.nil? %>
          <%= link_to 'Добавить файлы', setup_script_insints_path(:insint_id => current_user.insints.first.id), class: 'btn btn-outline-primary mb-3' %>
        <% else %>
          <%= link_to 'Удалить файлы', delete_script_insints_path(:insint_id => current_user.insints.first.id), class: 'btn btn-outline-danger mb-3' %>
        <% end %>
      <% else %>
        <% if current_user.insints.first.subdomen.present?%>
          <p>Регистрация настроена автоматически</p>
        <% else %>
          <%= link_to 'Добавить интеграцию', new_insint_path, class: 'btn btn-outline-primary mb-3' %>
        <% end %>
      <% end %>
    <% else %>
      <%= link_to 'Добавить интеграцию', new_insint_path, class: 'btn btn-outline-primary mb-3' %>
    <% end %>
  </div>
</div>
<div class="row mt-3">
  <div class="col">
  <h3>Регистрация <small><%= current_user.name%> (<%= current_user.subdomain%>)</small></h3>
  <p>Оплачен до - Бесплатно</p>
  <p><b>Название магазина: </b><%= @ins_title %></p>
  <p><b>Телефон:</b> <%= @ins_phone %></p>
  <p><b>Email:</b> <%= current_user.email %></p>
  </div>
  <div class="col">
    <p>Наш сервис бесплатен и мы будем рады если вы его поддержите. Стоимость сервера для работы сервиса составляет 750 руб в месяц.</p>
<iframe src="https://money.yandex.ru/quickpay/shop-widget?writer=seller&targets=%D0%9F%D0%BE%D0%B4%D0%B4%D0%B5%D1%80%D0%B6%D0%BA%D0%B0%20%D1%81%D0%B5%D1%80%D0%B2%D0%B8%D1%81%D0%B0%20k-kurs&targets-hint=&default-sum=450&button-text=11&payment-type-choice=on&hint=&successURL=&quickpay=shop&account=41001701618025" width="423" height="222" frameborder="0" allowtransparency="true" scrolling="no"></iframe>
  <p>Спасибо за участие!</p>
  </div>
</div>

app/views/dashboard/users.html.erb
<div class="row">
  <div class="col-3">
    <h1>Пользователи</h1>
    <p>Всего - <%= User.all.count%></p>
  </div>
  <%= search_form_for @q, url: url_for(controller: 'dashboard', action: 'users'), html: {class: 'form-inline col-9'}  do |f|%>
    <div class="form-group">
      <%= f.search_field :name_or_subdomain_or_email_cont_all, placeholder: 'Имя, домен, email', class: "form-control input-sm"%>
      <%= f.search_field :created_at_datebegin, placeholder: 'создан от', class: "form-control input-sm", autocomplete: "off" %>
      <%= f.search_field :valid_until_dateend, placeholder: 'valid до', class: "form-control input-sm", autocomplete: "off"%>
      <%= f.submit 'Поиск', class: 'btn btn-info' %>
      <%= link_to 'Сбросить',dashboard_users_path, class: 'btn btn-link' %>
    </div>
  <% end %>
</div>

<div class="table-responsive">
<table class="table table-hover table-condensed table-sm">
  <thead class="thead-light">
    <tr>
      <th>Имя</th>
      <th>Логин</th>
      <th>Email</th>
      <th>Создан</th>
      <th>Обновлён</th>
      <th>Последний вход</th>
      <th>Действует до</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.subdomain %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.in_time_zone.strftime("%d/%m/%Y %H:%M" ) %></td>
        <td><%= user.updated_at.in_time_zone.strftime("%d/%m/%Y %H:%M" ) %></td>
        <td><%= user.last_sign_in_at %></td>
        <td><%= user.valid_until %></td>
        <td><%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, dashboard_user_destroy_path(:user_id => user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
<div class="digg_pagination">
	<%= will_paginate @users %>
</div>