config/routes.rb
Rails.application.routes.draw do

  resources :kurs do
    collection do
      get :updatekur
      get :update_snippet
    end
  end
  root to: 'home#index'
  get '/insints' , to: 'home#index'
  resources :insints do
    collection do
      get :install
      get :uninstall
      get :login
      get :adminindex
      get :setup_script
      get :delete_script
      get :checkint
    end
  end

  constraints SubdomainConstraint do
    get '/dashboard/index' , to: 'dashboard#index'
    get '/dashboard/users', to: 'dashboard#users'
    get '/dashboard/test_email', to: 'dashboard#test_email'
    delete '/dashboard/user_destroy', to: 'dashboard#user_destroy'
  end # constraints

  devise_for :users, controllers: {
    registrations:  'users/registrations',
    sessions:       'users/sessions',
    passwords:      'users/passwords',
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<% unless current_page?(user_session_url) or current_page?(new_user_session_url) or current_page?(new_user_registration_url) or current_page?(insints_url) or current_page?(new_user_password_url) or current_page?(edit_user_password_url) %>
  <footer class="pt-4 pt-md-5">
    <div class="container">
      <div class="row">
        <div class="col-12 col-sm-3 text-center text-lg-left">
          <h5>K-kurs</h5>
          <ul class="list-unstyled text-small">
            <li>
              <a class="text-muted" href="+74997042035">84997052117</a>
            </li>
            <li>
              <a class="text-muted" href="+74997042035">88123392235</a>
            </li>
            <li>
              <a class="text-muted" href="mailto:k-comment.ru">info@ketago.com</a>
            </li>
          </ul>
          <small class="d-block mb-3 text-muted">&copy; 2019-2020</small>
        </div>
        <div class="col-3 col-md d-none d-md-block">
          <h5>Меню</h5>
          <ul class="list-unstyled text-small">
            <li>
              <a class="text-muted" href="/#service">О сервисе</a>
            </li>
            <li>
              <a class="text-muted" href="/#nastroika">Настройка</a>
            </li>
            <li>
              <a class="text-muted" href="/#o-nas">О нас</a>
            </li>
          </ul>
        </div>
        <div class="col-3 col-md d-none d-md-block">
          <h5>Способы оплаты</h5>
          <p>Сервис бесплатный</p>
        </div>
        <div class="col-3 col-md d-none d-md-block">
          <h5>Наши данные</h5>
          <ul class="list-unstyled text-small">
            <li>ИП Эмексизов Панаёт Алексеевич</li>
            <li>Свидетельство о регистрации - 313774610800128</li>
            <li>ИНН - 772745849012</li>
          </ul>
        </div>
      </div>
    </div>
  </footer>
<% end %>

app/views/layouts/_header.html.erb
<div class="index-header d-flex flex-column flex-md-row align-items-center p-2 px-md-4 bg-white box-shadow">
  <h4 class="my-0 mr-md-auto font-weight-normal text-center text-lg-left">
    <a class="logo-text" href="http://k-kurs.ru">
      <strong>K-kurs</strong> <span style="color: green;"><i class="fa fa-dollar"></i> <i class="fa fa-euro"></i> <i class="fa fa-gbp"></i></span>
    </a>
    <p>
      <small>курсы валют для InSales</small>
    </p>
  </h4>
  <nav class="my-md-0 mr-md-0 mr-lg-4 mb-3">
    <a class="p-2 text-dark" href="/#service">О сервисе</a>
    <a class="p-2 text-dark" href="/#nastroika">Настройка</a>
    <a class="p-2 text-dark" href="/#o-nas">О нас</a>
  </nav>
  <div class="clearfix">
    <%= link_to t('log_in'), new_session_path('user'), class: 'btn btn-primary float-left mr-2' %>
    <%= link_to t('sign_up'), new_registration_path('user'), class: 'btn btn-outline-primary float-right' %>
  </div>
</div>

app/views/layouts/_messages.html.erb
<div class="alert-devise">
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade show">
      <a href="#" class="close" data-dismiss="alert">&times;</a>
      <%= value.html_safe %>
    </div>
  <% end %>
</div>

app/views/layouts/_zammad.html.erb
<script src="https://helpdesk.irband.ru/assets/chat/chat.min.js"></script>
<script>
$(function() {
  new ZammadChat({
    title: '<strong>Служба поддержки</strong>',
    background: '#d1d1d1',
    fontSize: '12px',
    //debug: true,
    chatId: 3
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="google-site-verification" content="JAdvrsGLh-nEGgPcFgag17KocSuZTRpv_UpfqHDCrg8" />
    <meta name="yandex-verification" content="c669bf29e8e91cd6" />
    <title>K-kurs - курсы валют для insales</title>
    <meta name="description" content="курсы валют для insales"/>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application'%>
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker3.css"/>
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
       (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
       m[i].l=1*new Date();k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
       (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

       ym(62690881, "init", {
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true
       });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/62690881" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
<!-- Chatra {literal} -->
<script>
    (function(d, w, c) {
        w.ChatraID = 'PYE5YneQ7Ayept6cB';
        var s = d.createElement('script');
        w[c] = w[c] || function() {
            (w[c].q = w[c].q || []).push(arguments);
        };
        s.async = true;
        s.src = 'https://call.chatra.io/chatra.js';
        if (d.head) d.head.appendChild(s);
    })(document, window, 'Chatra');
</script>
<!-- /Chatra {/literal} -->
  </head>
  <body class="<% if current_page?(root_url) or current_page?(new_user_session_url) or current_page?(new_user_registration_url) or current_page?(insints_url)%>body-main<%end%>">
    <% unless current_page?(root_url) or current_page?(new_user_session_url) or current_page?(new_user_registration_url) or current_page?(insints_url)%>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="<%= root_path %>">K-kurs</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor02">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item <%= 'active' if current_page?(dashboard_index_path) %>">
              <a class="nav-link" href="<%= dashboard_index_path %>">Главная</a>
            </li>
            <li class="nav-item <%= 'active' if current_page?(kurs_path) %>">
              <a class="nav-link" href="<%= kurs_path %>">Курсы валют</a>
            </li>
            <% if current_admin %>
              <li class="nav-item <%= 'active' if current_page?(dashboard_users_path) %>">
                <a class="nav-link" href="<%= dashboard_users_path %>">Пользователи</a>
              </li>
              <li class="nav-item <%= 'active' if current_page?(adminindex_insints_path) %>">
                <a class="nav-link" href="<%= adminindex_insints_path %>">Интеграции</a>
              </li>
            <% end %>
          </ul>
          <ul class="navbar-nav">
            <li class="nav-item  dropdown">
              <% if current_user %>
                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">
                  <i class="fa fa-user-circle" aria-hidden="true"></i>
                  <%= current_user.name %>
                  <span class="caret"></span>
                </a>
                <ul class="dropdown-menu dropdown-user">
                  <li><%= link_to "Выйти", destroy_user_session_url, method: :delete %></li>
                </ul>
              <% end %>
            </li>
          </ul>
        </div>
      </nav>
    <% end %>

    <div class="container-fluid <% unless current_page?(root_url) or current_page?(new_user_session_url) or current_page?(new_user_registration_url) or current_page?(insints_url)%>p-5<% end %>">
      <%= render partial: "/layouts/messages"%>
      <%= yield %>
    </div>
    <%= render partial: "/layouts/zammad"%>
  </body>
</html>