config/routes.rb
Rails.application.routes.draw do

  resources :kurs do
    collection do
      get :updatekur
      get :update_snippet
    end
  end
  root to: 'home#index'
  get '/insints' , to: 'home#index'
  resources :insints do
    collection do
      get :install
      get :uninstall
      get :login
      get :adminindex
      get :setup_script
      get :delete_script
      get :checkint
    end
  end

  constraints SubdomainConstraint do
    get '/dashboard/index' , to: 'dashboard#index'
    get '/dashboard/users', to: 'dashboard#users'
    get '/dashboard/test_email', to: 'dashboard#test_email'
    delete '/dashboard/user_destroy', to: 'dashboard#user_destroy'
  end # constraints

  devise_for :users, controllers: {
    registrations:  'users/registrations',
    sessions:       'users/sessions',
    passwords:      'users/passwords',
  }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/kur.rb
class Kur < ApplicationRecord

  validates :date, uniqueness: true

  def self.updatekur
    puts "Обновляем курс "+"#{Time.zone.now}"
    url = "https://www.cbr-xml-daily.ru/daily_json.js"
    resp = RestClient.get(url)
    data = JSON.parse(resp)
    date = data['Date']
    puts date
    a = date.to_time.in_time_zone('Moscow') +10.minutes
    kur = Kur.where('date BETWEEN ? AND ?', a.beginning_of_day,  a.end_of_day).last
    valutes = data['Valute']
    # puts valutes
    valutes.each do |val|
      if val[0].downcase == 'gbp'
        @gbp = val[1]['Value']
      end
      if val[0].downcase == 'byn'
        @byn = val[1]['Value']
      end
      if val[0].downcase == 'usd'
        @usd = val[1]['Value']
      end
      if val[0].downcase == 'eur'
        @eur = val[1]['Value']
      end
      if val[0].downcase == 'kzt'
        @kzt = val[1]['Value']
      end
      if val[0].downcase == 'cny'
        @cny = val[1]['Value']
      end
      if val[0].downcase == 'uah'
        @uah = val[1]['Value']
      end
      if val[0].downcase == 'chf'
        @chf = val[1]['Value']
      end
      if val[0].downcase == 'jpy'
        @jpy = val[1]['Value']
      end
    end
    if kur.nil?
      Kur.create(:date => date, gbp: @gbp, byn: @byn, usd: @usd, eur: @eur, kzt: @kzt, cny: @cny, uah: @uah, chf: @chf, jpy: @jpy)
    else
      kur.update_attributes(gbp: @gbp, byn: @byn, usd: @usd, eur: @eur, kzt: @kzt, cny: @cny, uah: @uah, chf: @chf, jpy: @jpy)
    end
    puts "Закончили обновлять курс "+"#{Time.zone.now}"
  end

end

app/controllers/kurs_controller.rb
class KursController < ApplicationController

  before_action :authenticate_user! #, except: [:updatekur]
  before_action :set_kur, only: [:show, :edit, :update, :destroy]

  # GET /kurs
  # GET /kurs.json
  def index
    @search = Kur.ransack(params[:q])
    @search.sorts = 'id desc' if @search.sorts.empty?
    @kurs = @search.result.paginate(page: params[:page], per_page: 30)
  end

  # GET /kurs/1
  # GET /kurs/1.json
  def show
  end

  # GET /kurs/new
  def new
    if current_admin
      @kur = Kur.new
    else
      redirect_to dashboard_index_path
    end
  end

  # GET /kurs/1/edit
  def edit
  end

  # POST /kurs
  # POST /kurs.json
  def create
    @kur = Kur.new(kur_params)

    respond_to do |format|
      if @kur.save
        format.html { redirect_to @kur, notice: 'Kur was successfully created.' }
        format.json { render :show, status: :created, location: @kur }
      else
        format.html { render :new }
        format.json { render json: @kur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kurs/1
  # PATCH/PUT /kurs/1.json
  def update
    respond_to do |format|
      if @kur.update(kur_params)
        format.html { redirect_to @kur, notice: 'Kur was successfully updated.' }
        format.json { render :show, status: :ok, location: @kur }
      else
        format.html { render :edit }
        format.json { render json: @kur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kurs/1
  # DELETE /kurs/1.json
  def destroy
    @kur.destroy
    respond_to do |format|
      format.html { redirect_to kurs_url, notice: 'Kur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def updatekur
    Kur.updatekur
    flash[:notice] = 'Загрузили'
    redirect_to dashboard_index_path
  end

  def update_snippet
    Insint.update_kurs_snippet(current_user.id)
    flash[:notice] = 'Обновили сниппет'
    redirect_to dashboard_index_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_kur
      @kur = Kur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kur_params
      params.require(:kur).permit(:date, :gbp, :byn, :usd, :eur, :kzt, :cny, :uah, :chf, :jpy)
    end
end

app/helpers/kurs_helper.rb
module KursHelper
end

app/views/kurs/_form.html.erb
<%= simple_form_for(@kur) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :date %>
    <%= f.input :gbp %>
    <%= f.input :byn %>
    <%= f.input :usd %>
    <%= f.input :eur %>
    <%= f.input :kzt %>
    <%= f.input :cny %>
    <%= f.input :uah %>
    <%= f.input :chf %>
    <%= f.input :jpy %>
  </div>

  <div class="form-actions">
    <%# f.button :submit %>
  </div>
<% end %>

app/views/kurs/edit.html.erb
<h1>Editing Kur</h1>

<%= render 'form', kur: @kur %>

<%# link_to 'Show', @kur %> |
<%= link_to 'Back', kurs_path %>

app/views/kurs/index.html.erb
<div class="row">
  <div class="col-4"><h1>Курсы валют</h1></div>
</div>

<div class="table-responsive">
<table class="table table-hover table-condensed table-sm">
  <thead class="thead-light">
    <tr>
      <th>Date</th>
      <th>Gbp</th>
      <th>Byn</th>
      <th>Usd</th>
      <th>Eur</th>
      <th>Kzt</th>
      <th>Cny</th>
      <th>Uah</th>
      <th>Chf</th>
      <th>Jpy</th>
    </tr>
  </thead>

  <tbody>
    <% @kurs.each do |kur| %>
      <tr>
        <td><%= kur.date %></td>
        <td><%= kur.gbp %></td>
        <td><%= kur.byn %></td>
        <td><%= kur.usd %></td>
        <td><%= kur.eur %></td>
        <td><%= kur.kzt %></td>
        <td><%= kur.cny %></td>
        <td><%= kur.uah %></td>
        <td><%= kur.chf %></td>
        <td><%= kur.jpy %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div class="digg_pagination">
  <%= will_paginate @kurs %>
</div>

app/views/kurs/new.html.erb
<h1>New Kur</h1>

<%= render 'form', kur: @kur %>

<%= link_to 'Back', kurs_path %>

app/views/kurs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @kur.date %>
</p>

<p>
  <strong>Gbp:</strong>
  <%= @kur.gbp %>
</p>

<p>
  <strong>Byn:</strong>
  <%= @kur.byn %>
</p>

<p>
  <strong>Usd:</strong>
  <%= @kur.usd %>
</p>

<p>
  <strong>Eur:</strong>
  <%= @kur.eur %>
</p>

<p>
  <strong>Kzt:</strong>
  <%= @kur.kzt %>
</p>

<p>
  <strong>Cny:</strong>
  <%= @kur.cny %>
</p>

<p>
  <strong>Uah:</strong>
  <%= @kur.uah %>
</p>

<p>
  <strong>Chf:</strong>
  <%= @kur.chf %>
</p>

<p>
  <strong>Jpy:</strong>
  <%= @kur.jpy %>
</p>

<%# link_to 'Edit', edit_kur_path(@kur) %> |
<%= link_to 'Back', kurs_path %>